# Generated by Django 2.2.24 on 2021-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(help_text='Use o formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
